---
- name: Install Redis
  ansible.builtin.dnf:
    name: "{{ redis_rocky }}"
    state: latest

- name: Start and Enable Redis
  ansible.builtin.systemd_service:
    name: redis
    state: stopped
    enabled: true
