---
- hosts: '{{target|default("all")}}'
#  gather_facts: false 
  ignore_errors: true
  become: true
#  serial: 50
  vars:
    missing_agents: [] 
    
  tasks:

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: get installed services
      ansible.builtin.debug:
        msg: "{{ item.key }}" 
      loop: "{{ {'xdr': 'traps_pmd.service', 'zabbix': 'zabbix-agent2.service', 'tanium': 'taniumclient.service', 'qualys': 'qualys-cloud-agent.service', 'splunk': 'splunkd.service'} | dict2items }}"
      loop_control:
        label: "{{ item.value }}"
      when:  ansible_facts.services is defined and item.value not in ansible_facts.services
      ignore_errors: true

    - name: create list    
      ansible.builtin.set_fact:
        missing_agents: "{{ item.key }}"
      loop: "{{ {'xdr': 'traps_pmd.service', 'zabbix': 'zabbix-agent2.service', 'tanium': 'taniumclient.service', 'qualys': 'qualys-cloud-agent.service', 'splunk': 'splunkd.service'} | dict2items }}"
      loop_control:
        label: "{{ item.value }}"
      when:  ansible_facts.services is defined and item.value not in ansible_facts.services

    - name: show list
      ansible.builtin.debug:
        var: "{{ missing_agents }}"

    - ansible.builtin.include_role: 
        name: "{{ missing_agents }}"
      when: missing_agents is defined
      loop: "{{missing_agents}}"
