---
- name: Create inventory file 
  hosts: localhost
  gather_facts: false
  vars:
    input_inventory_file_yml: "/etc/ansible/dev_inventory2.yml"
    output_inventory_file_ini: "/etc/ansible/lower_dev.ini"

  tasks:

    - name: Convert inventory to INI format
      ansible.builtin.set_fact:
        ini_inventory: "{{ input_inventory_file_yml | inventory_to_ini }}"

    - name: Write static inventory to file
      ansible.builtin.copy:
        content: "{{ ini_inventory }}"
        dest: "{{ output_inventory_file_ini }}"

#  after_tasks:
#    - debug:
#        msg: "Static inventory file created at {{ output_inventory_file }}"
