---

- name: Run jobs and generate report
  hosts: all
  gather_facts: no
  order: sorted

#  collections:
#    - ansible.builtin
#    - community.general

  vars:
    # Location for job reports
    outdir: /tmp/reports
    # CSS styling for navbar: menu width, failed/missing colors
    nav_width: 200px
    failed_style: 'color:orangered'
    missing_style: 'color:grey;text-decoration:line-through'
    # Email options
    send_email: true
    smtp_host: smtprelay.example.com
    smtp_port: 25
    mail_from: "ansible@example.com"
    mail_to: "travis.worth@example.com,steven.example@example.com"
    mail_subject: "Ansible job report"
    # Uncomment these if authentication is required
    #smtp_user:
    #smtp_pass: 

  tasks:
    
    - name: Send email report from Ansible server
      delegate_to: localhost
      run_once: yes
      when: send_email
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user | default(omit) }}"
        password: "{{ smtp_pass | default(omit) }}"
        from: "{{ mail_from }}"
        to: "{{ mail_to }}"
        subject: "{{ mail_subject }}"
        subtype: html
        body: |
          <p>See attached for a detailed job report.</p>
          <p><strong>Successful hosts</strong>:<br><br>{{ hostvars['localhost']['success_list'] | join(' ') }}</p>
          <p style="color:red;"><strong>Failed hosts</strong>: <br><br>{{ hostvars['localhost']['failed_list'] | join(' ') }}</p>
          <p style="color:fuchsia;"><strong>Missing hosts</strong>: {{ hostvars['localhost']['missing_list'] | join(' ') }}</p>
          <p><i>Generated by playbook {{ playbook_dir }}/job_report.yaml on {{ hostvars['localhost']['date_str_pretty'] }}</i></p>
        attach:
          - "{{ outdir }}/job_report_{{ hostvars['localhost']['date_str'] }}.html"
