---
- hosts: '{{target|default("all")}}'
#  gather_facts: false 
  ignore_errors: true
  become: true
  serial: 50

  tasks:
    - name: Modify the file permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /mnt/diag
        - /mnt/solr-home
        - /mnt/logs
