---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Change user password
      ansible.builtin.user:
        name: root
        update_password: always
        password: "{{ vault_root_password | password_hash('sha512') }}"

    - name: Enable Root Login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin yes"
        state: present
        backup: yes
      become: yes

    - name: restart sshd service
      ansible.builtin.systemd_service:
        name: sshd
        state: restarted
