---
- hosts: '{{target|default("all")}}'
#  gather_facts: false 
  ignore_errors: true
  become: true
#  serial: 50
  tasks:
    - name: Check for available updates
      command: "yum check-update"
      register: yum_update_output
      changed_when: yum_update_output.rc == 100


    - name: create a reboot group
      group_by:
        key: requires_reboot
      when: yum_update_output.rc == 100

#    - name: Add element to a list
#      set_fact:
#        programming_languages: "{{ pending_updates + {{ groups['requires_reboot'] }} }}"

    - name: create a text file with my list of servers
      copy:
        content: |
          {{ groups['requires_reboot'] }}
        dest: /tmp/reboot_list.txt
      delegate_to: localhost

    - debug:
        var: groups['requires_reboot']
      run_once: true

    - name: Send Email if updates are available or if there's an error
      community.general.mail:
        host: smtprelay.example.com
        port: 25
        to:
        - Steve Example <steven.example@example.com>
        cc:
        - Travis Worth <travis.worth@example.com>
        - Adam Example <adam.example@example.com>
        subject: Yum Update Status
        body: "{{ lookup('file', '/tmp/reboot_list.txt') }}" 
#        body: See attached file for pending servers needing updates.
#        attach: /tmp/reboot_list.txt
      delegate_to: localhost
      run_once: true
