---

- name: Check if Splunk is already installed 
  ansible.builtin.stat:
    path: /opt/splunkforwarder
  register: register_splunk

- name: start fresh
  ansible.builtin.dnf:
    name: splunkforwarder
    state: removed
#  when: not register_splunk.stat.exists

- name: remove previous version of Spunk on "{{ ansible_hostname }}"
  ansible.builtin.file:
    path: /opt/splunkforwarder
    state: absent 
    force: true
#  when: not register_splunk.stat.exists

- name: Configure splunk group
  ansible.builtin.group:
    name: "{{ splunk_group }}"
    state: present
#  when: not register_splunk.stat.exists    

- name: Configure splunk user
  ansible.builtin.user:
    name: "{{ splunk_user }}"
    state: present
    createhome: no
    expires: no
    group: "{{ splunk_group }}"
    home: "{{ splunk_home }}"
#  when: not register_splunk.stat.exists

- ansible.builtin.import_tasks: install.yml
#  when: not register_splunk.stat.exists

#- import_tasks: config.yml
#  when: register_splunk.stat.exists
