---

- name: Check if Cortex installed correctly
  ansible.builtin.stat:
    path: /opt/traps
  register: register_traps

- name: start fresh
  ansible.builtin.dnf:
    name: cortex-agent
    state: removed
    disablerepo: '*'
#  when: not register_traps.stat.exists

- ansible.builtin.import_tasks: install.yml
#  when: not register_traps.stat.exists

- ansible.builtin.import_tasks: selinux.yml
  when: ansible_facts.selinux.status == 'enabled'

- name: restart traps service
  ansible.builtin.systemd_service:
    name: traps_pmd
    state: started
    enabled: true
