---
- name: install needed packages
  ansible.builtin.dnf: 
    name: yum-utils
- name: install security patches with yum
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
    security: true
...
