---
- name: install needed packages
  ansible.builtin.dnf:
    name:
    - yum-utils
    - python3-dnf
    state: present
- name: install security patches
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
    security: true
...
