---

- name: "4.5.2.1 | PATCH | Ensure default group for the root account is GID 0"
  ansible.builtin.user:
      name: root
      group: 0

- name: "4.5.2.2 | PATCH | Ensure root user umask is configured"
  ansible.builtin.lineinfile:
      path: /root/.bash_profile
      regexp: \s*umask
      line: "umask {{ rhel8cis_root_umask }}"

- name: "4.5.2.3 | PATCH | Ensure system accounts are secured"
  block:
      - name: "4.5.2.3 | PATCH | | Ensure system accounts are secured | Set nologin"
        when:
            - item.id != "root"
            - item.id != "sync"
            - item.id != "shutdown"
            - item.id != "halt"
            - item.id != "nfsnobody"
            - item.uid < rhel8cis_min_uid | int
            - item.shell != "      /bin/false"
            - item.shell != "      /usr/sbin/nologin"
        ansible.builtin.user:
            name: "{{ item.id }}"
            shell: /usr/sbin/nologin
        loop: "{{ rhel8cis_passwd }}"
        loop_control:
            label: "{{ item.id }}"

      - name: "4.5.2.3 | PATCH | | Ensure system accounts are secured | Lock accounts"
        when:
            - item.id != "root"
            - item.id != "sync"
            - item.id != "shutdown"
            - item.id != "halt"
            - item.id != "nfsnobody"
            - item.uid < rhel8cis_min_uid | int
            - item.shell != "      /bin/false"
            - item.shell != "      /usr/sbin/nologin"
        ansible.builtin.user:
            name: "{{ item.id }}"
            password_lock: true
        loop: "{{ rhel8cis_passwd }}"
        loop_control:
            label: "{{ item.id }}"

- name: "4.5.2.4 | PATCH | Ensure root password is set"
  ansible.builtin.debug:
      msg: "This is set as an assert in tasks/main"
