---

- name: "1.4.1 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  ansible.posix.sysctl:
      name: kernel.randomize_va_space
      value: '2'
      reload: true
      sysctl_file: /etc/sysctl.d/60-kernel_sysctl.conf
      sysctl_set: true
      ignoreerrors: true

- name: "1.4.2 | PATCH | Ensure ptrace_scope is restricted"
  ansible.posix.sysctl:
      name: kernel.yama.ptrace_scope
      value: '1'
      reload: true
      sysctl_file: /etc/sysctl.d/60-kernel_sysctl.conf
      sysctl_set: true
      ignoreerrors: true

- name: "1.4.3 | PATCH | Ensure core dump backtraces are disabled"
  ansible.builtin.lineinfile:
      path: /etc/systemd/coredump.conf
      regexp: 'ProcessSizeMax='
      line: 'ProcessSizeMax=0'

- name: "1.4.4 | PATCH | Ensure core dump storage is disabled"
  ansible.builtin.lineinfile:
      path: /etc/systemd/coredump.conf
      regexp: 'Storage='
      line: 'Storage=none'
