---

- name: "5.1.4 | PATCH | Ensure permissions on all logfiles are configured"
  block:
      - name: "5.1.4 | AUDIT | Ensure permissions on all logfiles are configured | find files"
        ansible.builtin.shell: find /var/log/ -type f -perm /g+wx,o+rwx -exec ls {} \;
        changed_when: false
        failed_when: false
        register: rhel8cis_5_1_4_logfiles

      - name: "5.1.4 | AUDIT | Ensure permissions on all logfiles are configured | set_fact"
        ansible.builtin.set_fact:
            rhel8cis_4_2_3_logfiles_flattened: "{{ rhel8cis_5_1_4_logfiles | json_query('stdout_lines[*]') | flatten }}"  # noqa: jinja[invalid]

      - name: "5.1.4 | PATCH | Ensure permissions on all logfiles are configured | change permissions"
        ansible.builtin.file:
            path: "{{ item }}"
            mode: '0640'
        loop: "{{ rhel8cis_5_1_4_logfiles_flattened }}"
