[sssd]
domains = EXAMPLE.ADP.AD
config_file_version = 2
services = nss, pam
default_domain_suffix = example.com

[domain/EXAMPLE.ADP.AD]
default_shell = /bin/bash
lookup_family_order = ipv4_only
krb5_store_password_if_offline = True
cache_credentials = True
krb5_realm = EXAMPLE.ADP.AD
realmd_tags = manages-system joined-with-adcli
id_provider = ad
fallback_homedir = /home/%u@%d
ad_domain = EXAMPLE.ADP.AD
use_fully_qualified_names = True
ldap_id_mapping = False
ldap_idmap_range_min = 16777216
ldap_idmap_range_max = 33554431
access_provider = ad
full_name_format = %1$s
ldap_schema = ad
subdomain_enumerate = none
ad_enabled_domains = EXAMPLE.ADP.AD
ad_gpo_access_control = disabled
ldap_group_member = member
dyndns_update = false
