---
# tasks file for bluecat-ipam-rest
- name: Acquire IP Address
  ansible.builtin.include_tasks: acquire_ip.yml
  when: state == 'present' or state == 'acquire'

- name: Lookup IP Address
  ansible.builtin.include_tasks: lookup_ip.yml
  when: state == 'get' or state == 'lookup'

- name: Release IP Address
  ansible.builtin.include_tasks: release_ip.yml
  when: state == 'absent' or state == 'release'



