#plugin: google.cloud.gcp_compute
plugin: gcp_compute
strict: true
cache_plugin: jsonfile
cache_timeout: 86400 
cache_connection: /etc/ansible/facts.d/facts

zones: # populate inventory with instances in these regions
  - us-east4-a
  - us-east4-b
  - us-central1-a
  - us-central1-c
#filters:
#  - status = RUNNING
#  - scheduling.automaticRestart = true AND status = RUNNING
service_account_file: /etc/ansible/inventory/gcp/service_account.json
auth_kind: serviceaccount
projects:
  - example-project-dev
  - example-cicd-project                
  - example-recon                     
  - example-project-prod         
  - example-test-project                 
keyed_groups:
  - key: application
  - key: zone
    prefix: zone
hostnames:
  - name
groups:
  development: "'dev' in name"
  sit: "'sit' in name"
  qua: "'qua' in name"
  uat: "'uat' in name"
  pfix: "'pfix' in name"
  prd: "'prd' in name"
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  #ansible_host: networkInterfaces[0].accessConfigs[0].natIP
    ansible_host: networkInterfaces[0].networkIP 
