---

- name: enable mariadb
  ansible.builtin.service:
    name: mariadb
    enabled: yes
  when: register_mariadb.stat.exists

- name: enable mariadb
  ansible.builtin.service:
    name: mysqld
    enabled: yes
  when: register_mysql.stat.exists

