---

- name: Send zabbix agent2 for el7 to /tmp on "{{ ansible_host }}"
  ansible.builtin.copy:
    src: "{{ zabbix_agent2_rpm_el7 }}"
    dest: /tmp/zabbix_agent2.rpm
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"

- name: Send zabbix agent2 for el8 to /tmp on "{{ ansible_host }}"
  ansible.builtin.copy:
    src: "{{ zabbix_agent2_rpm_el8 }}"
    dest: /tmp/zabbix_agent2.rpm
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

- name: Send zabbix agent2 for el9 to /tmp on "{{ ansible_host }}"
  ansible.builtin.copy:
    src: "{{ zabbix_agent2_rpm_el9 }}"
    dest: /tmp/zabbix_agent2.rpm
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9"

#- name: Install agent
#  command: yum localinstall -y /tmp/zabbix_agent2.rpm --nogpgcheck
#  async: 20

- name: Remove old agent
  ansible.builtin.dnf:
    name: zabbix-agent
    state: absent
    disable_gpg_check: true
    disablerepo: Exampleservices*,rhel-8*
    update_cache: false
#    use_backend: auto

- name: Install agent
  command: rpm -iU --nosignature /tmp/zabbix_agent2.rpm
#  ansible.builtin.dnf:
#    name: /tmp/zabbix_agent2.rpm
#    state: latest
#    disable_gpg_check: true
#    disablerepo: Exampleservices*,rhel-8*
#    update_cache: false
#    use_backend: auto
#  async: 20

#- name: Copy zabbix-agent.conf 
#  ansible.builtin.template:
#    src: "{{ zabbix_agent2_config }}"
#    dest: /etc/zabbix/zabbix_agent2.conf
#    force: true

#- name: Restart Zabbix Agent
#  systemd_service:
#    name: zabbix-agent2
#    state: restarted
#    enabled: true
