---

#- name: Create database user with name '{{ mysql_user }}' and password '{{ mysql_pass }}' with needed database privileges
#  community.mysql.mysql_user:
#    name: "{{ mysql_user }}"
#    password: "{{ mysql_pass }}"
#    priv: "*.*:ALL"
#    priv: 'REPLICATION CLIENT,PROCESS,SHOW DATABASES,SHOW VIEW ON *.*'
#    state: present
#
- name: Create database user with name '{{ mysql_user }}' and password '{{ mysql_pass }}' with needed database privileges
  command: mysql -e "CREATE USER 'zbx_monitor'@'%' IDENTIFIED BY 'Z@bb1x';"

- name: Create database user with name '{{ mysql_user }}' and password '{{ mysql_pass }}' with needed database privileges
  command: mysql -e "GRANT REPLICATION CLIENT,PROCESS,SHOW DATABASES,SHOW VIEW ON *.* TO 'zbx_monitor'@'%';"

