---


#- name: Check if ip is a valid IP address
#  ansible.builtin.set_fact:
#    data: "{{ 'svc_ips' is ansible.utils.ip }}"

- name: Checking ips 
  uri:
    url: "{{ svc_uris }}"
    method: GET 
  register: web_check

- name: show output
  debug: 
    var: web_check.content
