---


#- name: Check if ip is a valid IP address
#  ansible.builtin.set_fact:
#    data: "{{ 'example_ips' is ansible.utils.ip }}"

- name: Checking ips 
  ansible.builtin.uri:
    url: "{{ example_uris }}"
    method: GET 
  register: web_check

- name: show output
  ansible.builtin.debug: 
    var: web_check.content
