---

- name: Send Tanium to /tmp on "{{ ansible_hostname }}"
  ansible.builtin.copy:
    src: "{{ tanium_rpm_el7 }}"
    dest: /tmp/{{ tanium_rpm_el7 }}

#- name: Install package foo
#  command: rpm -i /tmp/{{ tanium_rpm }}

- name: Install Tanium 
  ansible.builtin.dnf:
    name: /tmp/{{ tanium_rpm_el7 }}
    state: present
    disable_gpg_check: true
  async: 60
  poll: 5

- name: Copy Tanium dat file to /opt/Tanium 
  ansible.builtin.copy:
    src: "{{ tanium_config }}"
    dest: /opt/Tanium/TaniumClient

- name: Restart Tanium service and set Enabled 
  ansible.builtin.systemd_service:
    name: taniumclient
    state: restarted
    enabled: true
