---

- name: Get all disks from existing VM
  community.vmware.vmware_guest_disk_info:
    validate_certs: False
    datacenter: '{{ data_center }}'
    name: '{{ vm_name  }}'
  register: existing_disk

- name: Get Backing datastore for desired disk id
  ansible.builtin.set_fact:
    disk_zero_datastore: "{{ item.value.backing_datastore }}"
  loop: "{ {{ existing_disk.guest_disk_info }} | dict2items }"
  when: item.key == '0'

- ansible.builtin.debug:
    msg: "{{ disk_zero_datastore }}"
  when: disk_zero_datastore is defined

- name: Get scsi controller type
  ansible.builtin.set_fact:
    scsi_type: "{{ item.value.controller_type }}"
  loop: "{ {{ existing_disk.guest_disk_info }} | dict2items }"
  when: item.key == '0'

- ansible.builtin.debug:
    msg: '{{ scsi_type }}'
  when: scsi_type is defined


- name: Get Unit Number
  ansible.builtin.set_fact:
    unit_number: "{{ item.value.unit_number }}"
  loop: "{ {{ existing_disk.guest_disk_info }} | dict2items }"
  when: item.key == '0'

- ansible.builtin.debug:
    msg: '{{ unit_number }}'
  when: unit_number is defined


- name: Get Disk + 30%
  ansible.builtin.set_fact:
    disc_size: "{{ item.value.capacity_in_kb|int *13/10| round(2, 'floor')|int }}"
  loop: "{ {{ existing_disk.guest_disk_info }} | dict2items }"
  when: item.key == '0'
  
- ansible.builtin.debug:
    msg: '{{ disc_size }}'
  when: disc_size is defined

#- name: Connect to VMWare and shutdown guest
#  community.vmware.vmware_guest:
#    validate_certs: no
#    datacenter: "{{ data_center }}"
#    name: "{{ vm_name }}"
#    state: shutdownguest
#  delegate_to: localhost
#  failed_when: vm_shutdown.instance.hw_power_status != 'poweredOff' and vm_shutdown.changed == false
#  register: vm_shutdown

#- name: Wait 300 seconds, but only start checking after 15 seconds
#  wait_for_connection:
#    delay: 15
#    timeout: 300

- name: Connect to VMWare and resize disk on VM
  community.vmware.vmware_guest_disk:
    validate_certs: no
    datacenter: "{{ data_center }}"
    name: "{{ vm_name }}"
    disk:
      - size_kb: "{{ disc_size|int }}"
        state: present
        unit_number: "{{ unit_number }}"
        scsi_controller: 0
        scsi_type: "{{ scsi_type }}"
  delegate_to: localhost
  register: disk_facts


- name: Extend the logical volume to take all remaining space of the PVs and resize the underlying filesystem
  community.general.lvol:
    vg: "{{ lvm_group }}"
    lv: "{{ item.name }}"
    size: 100%PVS
    resizefs: true
  loop:
   "{{ lvm_volumes }}"

- name: Create a volume group on top of /dev/sda3 and resize the volume group /dev/sda3 to the maximum possible
  community.general.lvg:
    vg: resizableVG
    pvs: /dev/sda3
    pvresize: true
